/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasAdmin;

import modelos.Usuario;
import vistasPdf.VentanOpcionesRetraso;

/**
 *
 * @author LENOVO
 */
public class VentanaOpciones extends javax.swing.JFrame {
    /**
     * Creates new form VentanaOpciones
     */
    public VentanaOpciones() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnRegistroUsuario = new javax.swing.JButton();
        btnGestionLibros = new javax.swing.JButton();
        btnGestionGeneros = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnDevoluciones = new javax.swing.JButton();
        btnRetraso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("OPCIONES");

        btnRegistroUsuario.setBackground(new java.awt.Color(0, 0, 102));
        btnRegistroUsuario.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnRegistroUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistroUsuario.setText("GESTIÓN USUARIOS");
        btnRegistroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroUsuarioActionPerformed(evt);
            }
        });

        btnGestionLibros.setBackground(new java.awt.Color(0, 0, 102));
        btnGestionLibros.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnGestionLibros.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionLibros.setText("GESTIÓN LIBROS");
        btnGestionLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionLibrosActionPerformed(evt);
            }
        });

        btnGestionGeneros.setBackground(new java.awt.Color(0, 0, 102));
        btnGestionGeneros.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnGestionGeneros.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionGeneros.setText("GESTIÓN GENEROS");
        btnGestionGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionGenerosActionPerformed(evt);
            }
        });

        btnHistorial.setBackground(new java.awt.Color(0, 0, 102));
        btnHistorial.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnHistorial.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorial.setText("HISTORIAL PRESTAMO");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });

        btnDevoluciones.setBackground(new java.awt.Color(0, 0, 102));
        btnDevoluciones.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnDevoluciones.setForeground(new java.awt.Color(255, 255, 255));
        btnDevoluciones.setText("HISTORIAL DEVOLUCIONES");
        btnDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionesActionPerformed(evt);
            }
        });

        btnRetraso.setBackground(new java.awt.Color(0, 0, 102));
        btnRetraso.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnRetraso.setForeground(new java.awt.Color(255, 255, 255));
        btnRetraso.setText("RETRASO");
        btnRetraso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrasoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel1)
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnDevoluciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGestionGeneros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGestionLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnHistorial))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(btnRetraso)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistroUsuario)
                    .addComponent(btnGestionLibros))
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionGeneros)
                    .addComponent(btnHistorial))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDevoluciones)
                    .addComponent(btnRetraso))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroUsuarioActionPerformed
        // TODO add your handling code here:
        VentanaRegistro ventana = new VentanaRegistro();
        ventana.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnRegistroUsuarioActionPerformed

    private void btnGestionLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionLibrosActionPerformed
        // TODO add your handling code here:
        VentanaRegistroLibros ventana = new VentanaRegistroLibros();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionLibrosActionPerformed

    private void btnGestionGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionGenerosActionPerformed
        // TODO add your handling code here:
        VentanaRegistroGenero ventana = new VentanaRegistroGenero();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionGenerosActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
        VentanaHistorialPrestamo ventana = new VentanaHistorialPrestamo();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionesActionPerformed
        // TODO add your handling code here:
        VentanaHistorialDevoluciones ventana = new VentanaHistorialDevoluciones();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDevolucionesActionPerformed

    private void btnRetrasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrasoActionPerformed
        // TODO add your handling code here:
        VentanOpcionesRetraso ventana = new VentanOpcionesRetraso();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRetrasoActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevoluciones;
    private javax.swing.JButton btnGestionGeneros;
    private javax.swing.JButton btnGestionLibros;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnRegistroUsuario;
    private javax.swing.JButton btnRetraso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
