/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasAdmin;

import controladores.ControladorGenero;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelos.Genero;

/**
 *
 * @author LENOVO
 */
public class VentanaRegistroGenero extends javax.swing.JFrame {
    
    private final ControladorGenero controlador;
    private TableRowSorter<DefaultTableModel> sorter;
            

    /**
     * Creates new form VentanaRegistroGenero
     */
    public VentanaRegistroGenero() {
        initComponents();
        setLocationRelativeTo(this);
        controlador = new ControladorGenero();
        llenarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblGestionGeneros = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreGenero = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaGeneros = new javax.swing.JTable();
        lblBuscar = new javax.swing.JLabel();
        txtBuscarGenero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 102));

        lblGestionGeneros.setBackground(new java.awt.Color(255, 255, 255));
        lblGestionGeneros.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblGestionGeneros.setForeground(new java.awt.Color(0, 0, 102));
        lblGestionGeneros.setText("GESTIÓN GENEROS");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Nombre genero");

        txtNombreGenero.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreGenero.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        txtNombreGenero.setForeground(new java.awt.Color(0, 0, 0));

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 102));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI Historic", 1, 15)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(0, 0, 102));
        btnEditar.setFont(new java.awt.Font("Segoe UI Historic", 1, 15)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(0, 0, 102));
        btnEliminar.setFont(new java.awt.Font("Segoe UI Historic", 1, 15)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setFont(new java.awt.Font("Segoe UI Historic", 1, 15)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 102));
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        tablaGeneros.setBackground(new java.awt.Color(255, 255, 255));
        tablaGeneros.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        tablaGeneros.setForeground(new java.awt.Color(0, 0, 0));
        tablaGeneros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaGeneros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaGenerosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaGeneros);

        lblBuscar.setBackground(new java.awt.Color(255, 255, 255));
        lblBuscar.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(0, 0, 102));
        lblBuscar.setText("Buscar");

        txtBuscarGenero.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscarGenero.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        txtBuscarGenero.setForeground(new java.awt.Color(0, 0, 102));
        txtBuscarGenero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarGeneroKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRegistrar)
                                    .addComponent(btnEditar)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombreGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(btnRegresar)))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(101, 101, 101)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblGestionGeneros)
                        .addGap(409, 409, 409))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblGestionGeneros)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombreGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addComponent(btnRegistrar)
                        .addGap(12, 12, 12)
                        .addComponent(btnEliminar)
                        .addGap(17, 17, 17)
                        .addComponent(btnEditar)
                        .addGap(62, 62, 62)
                        .addComponent(btnRegresar)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBuscar)
                            .addComponent(txtBuscarGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String nombreGenero = txtNombreGenero.getText().trim();
        
        if(validarCampos()){
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos");
            return;
        }
        Genero genero = (Genero) controlador.buscarObject(nombreGenero);
        if(genero != null){
            JOptionPane.showMessageDialog(null, "Ya hay un genero con ese nombre");
            return;
        }
        
        try{
            Genero genero1 = new Genero(nombreGenero);
            controlador.agregarObjeto(genero1);
            JOptionPane.showMessageDialog(null, "Genero registrado correctamente");
            llenarTabla();
            limpiarCampos();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "No se pudo registrar el genero");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:       
        if(validarCampos()){
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos");
            return;
        }
        String nombreGenero = txtNombreGenero.getText().trim();
        
        int selec = tablaGeneros.getSelectedRow();
        if(selec >= 0){
            int idGenero = (int) tablaGeneros.getModel().getValueAt(selec, 0);
            
            try{
                Genero genero = new Genero(idGenero, nombreGenero);
                
                controlador.editarObject(genero);
                JOptionPane.showMessageDialog(null, "Genero editado correctamente");
                llenarTabla();
                limpiarCampos();
            }catch (SQLException ex){
                JOptionPane.showMessageDialog(null, "No se pudo editar el genero");
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int selec = tablaGeneros.getSelectedRow();
        
        if(selec >= 0){
            int idGenero = (int) tablaGeneros.getModel().getValueAt(selec, 0);
            
            try{
                controlador.eliminarObjeto(idGenero);
                llenarTabla();
                JOptionPane.showMessageDialog(null, "Genero eliminado correctamente");
                limpiarCampos();
                
            }catch (SQLException ex){
                JOptionPane.showMessageDialog(null, "No se pudo eliminar el genero");
                limpiarCampos();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscarGeneroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarGeneroKeyReleased
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_txtBuscarGeneroKeyReleased

    private void tablaGenerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaGenerosMouseClicked
        // TODO add your handling code here:
        int seleccion = tablaGeneros.getSelectedRow();
        
        txtNombreGenero.setText(tablaGeneros.getValueAt(seleccion, 1).toString());
        
    }//GEN-LAST:event_tablaGenerosMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaOpciones ventana = new VentanaOpciones();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void llenarTabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        
        ArrayList<Object> generos = controlador.listarObjeto();
        
        modelo.setColumnIdentifiers(new Object[]{
            "ID genero", "Nombre genero"
        });
        tablaGeneros.setModel(modelo);
        tablaGeneros.setAutoCreateRowSorter(true);
        sorter = new TableRowSorter<>(modelo);
        tablaGeneros.setRowSorter(sorter);
        
        for (int i = 0; i < generos.size(); i++) {
           Genero genero = (Genero) generos.get(i);
            modelo.addRow(new Object[]{
                genero.getIdGenero(),
                genero.getNombreGenero()
            });
        }
        
    }
    
    private void filtrar(){
        String filterText = txtBuscarGenero.getText().trim();
        
        RowFilter<Object, Object> idGenero = RowFilter.regexFilter(filterText.trim(), 0);
        RowFilter<Object, Object> nombreGenero = RowFilter.regexFilter(filterText.trim(), 1);
        
        sorter.setRowFilter(RowFilter.orFilter(Arrays.asList(idGenero, nombreGenero)));
    }
    private boolean validarCampos(){
        return (txtNombreGenero.getText().isEmpty());
    }
    private void limpiarCampos() {
        txtNombreGenero.setText("");
        
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblGestionGeneros;
    private javax.swing.JTable tablaGeneros;
    private javax.swing.JTextField txtBuscarGenero;
    private javax.swing.JTextField txtNombreGenero;
    // End of variables declaration//GEN-END:variables
}
