/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasAdmin;

import controladores.ControladorPrestamo;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelos.Prestamo;
import modelos.Usuario;
import vistasPdf.VentanaGeneral;
import vistasPdf.VentanaReporteFecha;
import vistasPdf.VentanaReporteUsuario;
import vistasPdf.VentanaReporteUsuarioFecha;

/**
 *
 * @author LENOVO
 */
public class VentanaHistorialPrestamo extends javax.swing.JFrame {

    ControladorPrestamo controlador;

    /**
     * Creates new form VentanaHistorialPrestamo
     */
    public VentanaHistorialPrestamo() {
        initComponents();
        setLocationRelativeTo(this);
        controlador = new ControladorPrestamo();
        llenarTabla();
    }

    private void llenarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();

        ArrayList<Prestamo> prestamos = controlador.listarTodosPrestamos();
        modelo.setColumnIdentifiers(new Object[]{
            "Cedula usuario", "Usuario", "ISBN", "Título", "Cantidad", "Fecha prestamo", "Fecha Vencimiento"
        });
        tablaHistorial.setModel(modelo);

        for (Prestamo prestamo : prestamos) {
            modelo.addRow(new Object[]{
                prestamo.getUsuario().getCedula(),
                prestamo.getUsuario().getNombre(),
                prestamo.getLibro().getISBN(),
                prestamo.getLibro().getTitulo(),
                prestamo.getCantidadLibro(),
                prestamo.getFechaPrestamo(),
                prestamo.getFechaLimite()
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();
        cbxOpcionesReportes = new javax.swing.JComboBox<>();
        btnReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaHistorial);

        cbxOpcionesReportes.setBackground(new java.awt.Color(255, 255, 255));
        cbxOpcionesReportes.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        cbxOpcionesReportes.setForeground(new java.awt.Color(0, 0, 0));
        cbxOpcionesReportes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Fecha", "Usuario", "Fecha y usuario", "General", "Retrasos" }));

        btnReporte.setBackground(new java.awt.Color(0, 0, 102));
        btnReporte.setFont(new java.awt.Font("Segoe UI Historic", 1, 15)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte.setText("REALIZAR REPORTE");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(cbxOpcionesReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporte)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(cbxOpcionesReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnReporte)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        switch (cbxOpcionesReportes.getSelectedIndex()) {
            case 1:
                new VentanaReporteFecha().setVisible(true);
                this.dispose();
                break;
            case 2:
                new VentanaReporteUsuario().setVisible(true);
                this.dispose();
                break;
            case 3:
                new VentanaReporteUsuarioFecha().setVisible(true);
                break;
            case 4:
                new VentanaGeneral().setVisible(true);
                this.dispose();
                break;
        }
    }//GEN-LAST:event_btnReporteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporte;
    private javax.swing.JComboBox<String> cbxOpcionesReportes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaHistorial;
    // End of variables declaration//GEN-END:variables
}
