/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasUsuario;

import controladores.ControladorPrestamo;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelos.Prestamo;
import modelos.Usuario;

/**
 *
 * @author LENOVO
 */
public class VentanaListadoPrestamo extends javax.swing.JFrame {

    Usuario usuario;
    ControladorPrestamo controlador;
    private TableRowSorter<DefaultTableModel> sorter;

    /**
     * Creates new form VentanaListadoPrestamo
     */
    public VentanaListadoPrestamo(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        setLocationRelativeTo(this);
        controlador = new ControladorPrestamo();
        llenarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPrestamo = new javax.swing.JTable();
        btnRealizarDevolucion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaPrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPrestamo);

        btnRealizarDevolucion.setBackground(new java.awt.Color(0, 0, 102));
        btnRealizarDevolucion.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnRealizarDevolucion.setForeground(new java.awt.Color(255, 255, 255));
        btnRealizarDevolucion.setText("REALIZAR DEVOLUCION");
        btnRealizarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarDevolucionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                .addGap(77, 77, 77))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnRealizarDevolucion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRealizarDevolucion)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarDevolucionActionPerformed
        // TODO add your handling code here:
        int selec = tablaPrestamo.getSelectedRow();

        if (selec >= 0) {
            int idPrestamo = (int) tablaPrestamo.getModel().getValueAt(selec, 0);
            Prestamo prestamo = controlador.seleccionarPrestamo(idPrestamo);
            controlador.delvoverPrestamo(prestamo);
            llenarTabla();
            JOptionPane.showMessageDialog(null, "Devolucion realizada");

        } else {
            JOptionPane.showMessageDialog(null, "Sleecionar un prestamo de la tabla");
        }

    }//GEN-LAST:event_btnRealizarDevolucionActionPerformed

    private void llenarTabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        
        ArrayList<Prestamo> prestamos = controlador.listarUsuarioPrestamo(usuario);
        modelo.setColumnIdentifiers(new Object[]{
            "Id prestamo","ISBN", "Título","Cantidad", "Fecha prestamo", "Fecha vencimiento"
        });
        tablaPrestamo.setModel(modelo);
        tablaPrestamo.setAutoCreateRowSorter(true);
        sorter = new TableRowSorter<>(modelo);
        tablaPrestamo.setRowSorter(sorter);
        
        for (Prestamo prestamo : prestamos){
            modelo.addRow(new Object[]{
                prestamo.getId(),
                prestamo.getLibro().getISBN(),
                prestamo.getLibro().getTitulo(),
                prestamo.getCantidadLibro(),
                prestamo.getFechaPrestamo(),
                prestamo.getFechaLimite()
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizarDevolucion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPrestamo;
    // End of variables declaration//GEN-END:variables
}
