/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasUsuario;

import controladores.ControladorLibro;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelos.Libro;
import modelos.Usuario;
import vistasUsuario.VentanaPrestamo;

/**
 *
 * @author LENOVO
 */
public class VentanaListadoLibros extends javax.swing.JFrame {
    
    Usuario usuario;
    ControladorLibro controlador;
    
    private TableRowSorter<DefaultTableModel>  sorter;

    /**
     * Creates new form VentanaListadoLibros
     */
    public VentanaListadoLibros(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        setLocationRelativeTo(this);
        controlador = new ControladorLibro();
        llenarTabla();
    }
    
    
    private final void llenarTabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        
        ArrayList<Object> libros = controlador.listarObject();
        modelo.setColumnIdentifiers(new Object[]{
            "ISBN", "Titulo", "Autor", "Genero", "Año publicacion"
        });
        
        tablaLibros.setModel(modelo);
        tablaLibros.setAutoCreateRowSorter(true);
        sorter = new TableRowSorter<>(modelo);
        tablaLibros.setRowSorter(sorter);
        
        for (int i = 0; i < libros.size(); i++) {
            Libro libro = (Libro) libros.get(i);
            modelo.addRow(new Object[]{
                libro.getISBN(),
                libro.getTitulo(),
                libro.getAutor(),
                libro.getGenero().getNombreGenero(),
                libro.getAnio(),
            });
        }
        
    }
    
    private void filtro(){
        String filtro = txtBuscar.getText();
        
        RowFilter<Object, Object>  isbn = RowFilter.regexFilter(filtro.trim(), 0);
        RowFilter<Object, Object>  titulo = RowFilter.regexFilter(filtro.trim(), 1);
        RowFilter<Object, Object>  autor = RowFilter.regexFilter(filtro.trim(), 3);
        RowFilter<Object, Object>  genero = RowFilter.regexFilter(filtro.trim(), 4);
        RowFilter<Object, Object>  anioPublicacion = RowFilter.regexFilter(filtro.trim(), 5);
        RowFilter<Object, Object>  copias = RowFilter.regexFilter(filtro.trim(), 6);
        
        sorter.setRowFilter(RowFilter.orFilter(Arrays.asList(isbn, titulo, autor, genero, anioPublicacion, copias)));

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        btnRealizarPrestamo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaLibros.setBackground(new java.awt.Color(255, 255, 255));
        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaLibros);

        btnRealizarPrestamo.setBackground(new java.awt.Color(0, 0, 153));
        btnRealizarPrestamo.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnRealizarPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnRealizarPrestamo.setText("REALIZAR PRESTAMO");
        btnRealizarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPrestamoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Buscar");

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnRealizarPrestamo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRealizarPrestamo)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPrestamoActionPerformed
        // TODO add your handling code here:
        int selec = tablaLibros.getSelectedRow();
        
        if(selec >= 0){
            String isbn = tablaLibros.getModel().getValueAt(selec, 0).toString();
            Libro libro = (Libro) controlador.buscarObjeto(isbn);
            
            if (libro != null){
                new VentanaPrestamo(usuario, libro).setVisible(true);
                
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe de seleccionar un libro de la tabla");
        }
    }//GEN-LAST:event_btnRealizarPrestamoActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        filtro();
    }//GEN-LAST:event_txtBuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizarPrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaLibros;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
