/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasPdf;

import controladores.ControladorPdf;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import vistasAdmin.VentanaHistorialDevoluciones;
import vistasAdmin.VentanaHistorialPrestamo;

/**
 *
 * @author LENOVO
 */
public class VentanaReporteFechaRetraso extends javax.swing.JFrame {
    ControladorPdf controlador;


    /**
     * Creates new form VentanaGeneral
     */
    public VentanaReporteFechaRetraso() {
        initComponents();
        setLocationRelativeTo(this);
        controlador = new ControladorPdf();
    }
    
    private boolean validarCampos() {
        return (txtTituloReporte.getText().isEmpty());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFechaFinal = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblReporteGeneral = new javax.swing.JLabel();
        lblTituloReporte = new javax.swing.JLabel();
        txtTituloReporte = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        JDateFechaInicio = new com.toedter.calendar.JDateChooser();
        JDateFechaFinal = new com.toedter.calendar.JDateChooser();
        lblFechaInicio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFechaFinal.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 102));

        lblReporteGeneral.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblReporteGeneral.setForeground(new java.awt.Color(0, 0, 102));
        lblReporteGeneral.setText("REPORTE FECHA");

        lblTituloReporte.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        lblTituloReporte.setForeground(new java.awt.Color(0, 0, 102));
        lblTituloReporte.setText("Titulo reporte");

        txtTituloReporte.setBackground(new java.awt.Color(255, 255, 255));
        txtTituloReporte.setForeground(new java.awt.Color(0, 0, 0));

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setFont(new java.awt.Font("Segoe UI Historic", 1, 15)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 102));
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnGenerar.setBackground(new java.awt.Color(0, 0, 102));
        btnGenerar.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("GENERAR");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        lblFechaInicio.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        lblFechaInicio.setForeground(new java.awt.Color(0, 0, 102));
        lblFechaInicio.setText("Fecha Inicio");

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Fecha final");

        javax.swing.GroupLayout lblFechaFinalLayout = new javax.swing.GroupLayout(lblFechaFinal);
        lblFechaFinal.setLayout(lblFechaFinalLayout);
        lblFechaFinalLayout.setHorizontalGroup(
            lblFechaFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblFechaFinalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(lblFechaFinalLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(btnGenerar)
                .addGap(163, 163, 163))
            .addGroup(lblFechaFinalLayout.createSequentialGroup()
                .addGroup(lblFechaFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblFechaFinalLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(lblFechaFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloReporte)
                            .addComponent(lblFechaInicio)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addGroup(lblFechaFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JDateFechaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JDateFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTituloReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)))
                    .addGroup(lblFechaFinalLayout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(lblReporteGeneral)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lblFechaFinalLayout.setVerticalGroup(
            lblFechaFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblFechaFinalLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblReporteGeneral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(lblFechaFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloReporte)
                    .addComponent(txtTituloReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(lblFechaFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JDateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaInicio))
                .addGap(61, 61, 61)
                .addGroup(lblFechaFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblFechaFinalLayout.createSequentialGroup()
                        .addComponent(JDateFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                        .addGroup(lblFechaFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegresar)
                            .addComponent(btnGenerar))
                        .addGap(113, 113, 113))
                    .addGroup(lblFechaFinalLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFechaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        if(validarCampos()){
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos.");
            return;
        }
        
        String tituloReporte = txtTituloReporte.getText().trim();
        Date fecha1 = JDateFechaInicio.getDate();
        Date fecha2 = JDateFechaFinal.getDate();
        
        LocalDate FechaInicio = fecha1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate FechaFinal = fecha2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        
        
        
        boolean success = controlador.generarPDFRetrasoPorFecha(FechaInicio, FechaFinal, tituloReporte);
        
        if(success){
            JOptionPane.showMessageDialog(null, "Reporte generado");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No se encontraron datos para generar el reporte");
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaHistorialDevoluciones ventana = new VentanaHistorialDevoluciones();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDateFechaFinal;
    private com.toedter.calendar.JDateChooser JDateFechaInicio;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel lblFechaFinal;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblReporteGeneral;
    private javax.swing.JLabel lblTituloReporte;
    private javax.swing.JTextField txtTituloReporte;
    // End of variables declaration//GEN-END:variables
}
