/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasPdf;

import controladores.ControladorPdf;
import controladores.ControladorUsuario;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Usuario;
import vistasAdmin.VentanaHistorialPrestamo;

/**
 *
 * @author LENOVO
 */
public class VentanaReporteUsuarioFecha extends javax.swing.JFrame {
    ControladorPdf controlador;
    ControladorUsuario controladorU;
    /**
     * Creates new form VentanaReporteUsuario
     */
    public VentanaReporteUsuarioFecha() {
        initComponents();
        setLocationRelativeTo(this);
        controlador = new ControladorPdf();
        controladorU = new ControladorUsuario();
        llenarTabla();
    }
    private boolean validarCampos() {
        return (txtTituloReporte.getText().isEmpty() || txtCedula.getText().isEmpty());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblReporteUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        lblCedula = new javax.swing.JLabel();
        lblTituloReporte = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtTituloReporte = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaFinal = new javax.swing.JLabel();
        jDateFechaInicio = new com.toedter.calendar.JDateChooser();
        jDateFechaFinal = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblReporteUsuario.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblReporteUsuario.setForeground(new java.awt.Color(0, 0, 102));
        lblReporteUsuario.setText("GENERAR REPORTE USUARIO Y FECHA");

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaUsuarios);

        lblCedula.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(0, 0, 102));
        lblCedula.setText("Cédula usuario");

        lblTituloReporte.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        lblTituloReporte.setForeground(new java.awt.Color(0, 0, 102));
        lblTituloReporte.setText("Título reporte");

        txtCedula.setBackground(new java.awt.Color(255, 255, 255));
        txtCedula.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(0, 0, 0));

        txtTituloReporte.setBackground(new java.awt.Color(255, 255, 255));
        txtTituloReporte.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        txtTituloReporte.setForeground(new java.awt.Color(0, 0, 0));

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 102));
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnGenerar.setBackground(new java.awt.Color(0, 0, 102));
        btnGenerar.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("GENERAR");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        lblFechaInicio.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        lblFechaInicio.setForeground(new java.awt.Color(0, 0, 102));
        lblFechaInicio.setText("Fecha Inicio");

        lblFechaFinal.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        lblFechaFinal.setForeground(new java.awt.Color(0, 0, 102));
        lblFechaFinal.setText("Fecha Final");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(lblReporteUsuario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblCedula)
                                    .addGap(57, 57, 57)
                                    .addComponent(txtCedula))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTituloReporte)
                                        .addComponent(lblFechaInicio)
                                        .addComponent(lblFechaFinal))
                                    .addGap(67, 67, 67)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTituloReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                        .addComponent(jDateFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jDateFechaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerar)
                .addGap(149, 149, 149))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblReporteUsuario)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloReporte)
                    .addComponent(txtTituloReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaInicio)
                    .addComponent(jDateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaFinal)
                    .addComponent(jDateFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGenerar)
                        .addGap(115, 115, 115))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaHistorialPrestamo ventana = new VentanaHistorialPrestamo();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        if(validarCampos()){
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos");
            return;
        }
        String tituloReporte = txtTituloReporte.getText().trim();
        String cedula = txtCedula.getText().trim();
        Date fecha1 =  jDateFechaInicio.getDate();
        Date fecha2 = jDateFechaFinal.getDate();
        
        LocalDate FechaInicio = fecha1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate FechaFinal = fecha2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        boolean success = controlador.generarPDFPrestamoPorUsuarioyFecha(cedula, FechaInicio, FechaFinal, tituloReporte);
        
        if(success){
            JOptionPane.showMessageDialog(null, "Reporte generado");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No se encontraron datos para generar el reporte");
        }
        
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void llenarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();

        ArrayList<Object> usuarios = controladorU.listarObjectos();
        modelo.setColumnIdentifiers(new Object[]{
            "Cédula", "Nombre",
        });

        tablaUsuarios.setModel(modelo);

        for (int i = 0; i < usuarios.size(); i++) {
            Usuario usuario = (Usuario) usuarios.get(i);
            modelo.addRow(new Object[]{
                usuario.getCedula(),
                usuario.getNombre(),
            });

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnRegresar;
    private com.toedter.calendar.JDateChooser jDateFechaFinal;
    private com.toedter.calendar.JDateChooser jDateFechaInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblFechaFinal;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblReporteUsuario;
    private javax.swing.JLabel lblTituloReporte;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtTituloReporte;
    // End of variables declaration//GEN-END:variables
}
